@startuml
Game -> Game:registerPlayers
Game -> UI: playerNum = promptNumeric("Type number of players:")
loop playerNum > players.size()
Game -> IO: name = promptText("Type player name:")
Game -> IO: balance = promptText("Type player name:")
Game -> Player: player = new(name, balance)
Game -> Game: addPlayer(player)
end

@enduml